### ISSUE TITLE
Brainstorm on parallelism

### ISSUE THREAD

**Issue by juliohm** [JuliaPOMDP/POMDPs.jl#118]
In the POMDPs framework, there is lots of room for parallelism. From embarrassingly parallel updates in particles filters to tricky updates in Monte Carlo tree searches, it would be great to have better support for running many generative models in parallel.

I am opening this issue to initialize a discussion on the topic. Have you considered it already? What are the main candidates for optimization in the current packages?

**Comment by mykelk** [comment]
For many of our problems, we run tons of single-threaded Monte Carlo simulations in parallel to evaluate our solution approach. It is generally better to run a ton of single threaded solvers in parallel than a ton of multi-threaded solvers in parallel. However, if we're just running a bunch of simulations in series, then it can make sense to take advantage of parallelism. So, I think it would be good to support parallelism in the solvers, but it would be good to be able to turn it off. Does that make sense?

**Comment by juliohm** [comment]
Hi Mykel, I fully agree with being able to turn it off, or have it off by default. Parallelism with a single computing node (shared memory) should not be very difficult to achieve, the challenge is to take advantage of computing clusters and dispatch all those calls of generative models in different nodes (distributed memory). Would that be something of your interest?

I believe that the current API could be refactored somehow to accommodate computing clusters, it is a lot of work though. For example, if I take a minimal example with one of the solvers and try to run Julia with multiple workers `julia -p auto` I get errors saying that POMDP objects are not defined in the worker nodes, etc. Maybe we could start looking at Julia parallel capabilities to make the packages even more awesome.

**Comment by mykelk** [comment]
I think that would be awesome to look at. It hasn't been a major focus at SISL yet, but I think @rejuvyesh looked at parallelism to some extent for MCVI. He might have some comments.

**Comment by zsunberg** [comment]
Yeah, this would be really cool. We should define exactly which kinds of parallelism we would like to support, and identify what is needed for that. My initial intuition says that the core POMDPs interface will be compatible with parallelism as is, and it would be best to implement parallel features in other packages that use POMDPs.jl rather than the core package so that we don't overcommit to one vision of parallelism.

Coarse parallelism at the `simulate` level makes a lot of sense for online solvers. This is definitely possible now - I do it a lot, but the burden of setting it up falls on the experimenter - it would be very useful to have a package that launches a ton of simulations on different nodes (or just different processes). The challenge would be creating a flexible interface for specifying what you want to get back from these simulations. In my experience this has been surprisingly complicated and would require a lot of thought.

Parallelism in tree solvers would also be interesting to pursue, and would be really important for any implementation running in real time on a test vehicle for instance, but it is not as trivial as simulation-based parallelism and is not as necessary since online solvers can be evaluated with parallel simulations.

The most pressing need for parallelism as part of a package is in MCVI. The kinds of problems that MCVI is usually good at solving involve very simple and fast generate_sor implementations, so it would be best to have shared-memory thread-level parallelism. There does appear to be some support for this http://docs.julialang.org/en/release-0.5/manual/parallel-computing/#multi-threading-experimental, but there may be some special requirements for generate_sor if this is used.

**Comment by juliohm** [comment]
All very good points :+1:  I am closing the issue as it is already in our minds. Next time I use the POMDP solvers for my research, I will try to submit a PR.
