### ISSUE TITLE
O and T functions

### ISSUE THREAD

**Issue by dressel** [JuliaPOMDP/POMDPs.jl#172]
I feel like there should be O and T functions defined, for a couple reasons. First, it is more intuitive. Second, it might lead to performance gains.

For the first, consider the following examples that yield O(a, s', o) and T(s, a, s'):

```
od = observation(pomdp, a, sp)
po = pdf(od, o)

td = transition(pomdp, s, a)
pp = pdf(td, sp)
```

This is verbose. I think one of the selling points of POMDPs.jl is to be able to read and prototype solvers quickly. The following would be better:

```
po = O(pomdp, a, sp, o)
pp = T(pomdp, s, a, sp)
```

None of the underlying code needs to change. Couldn't we just implement the following?

```
function O(pomdp, a, sp, o)
    od = observation(pomdp, a, sp)
    po = pdf(od, o)
end
```

There might be computational benefits too. If `observation` returns a vector, we might be allocating memory every time we query an observation probability. If they wanted to, the user could re-define `O` for their problem to avoid this.

**Comment by zsunberg** [comment]
Thanks for proposing this - it seems like it would make some code more elegant and readable, and elegance and readability matters.

First, note that a similar shortcut is already implemented as `ParticleFilters.obs_weight`, except that in `obs_weight`, the documentation explicitly says that it doesn't need to be normalized.

Also note, that you can currently evaluate the PDF in one line:
```julia
po = pdf(observation(pomdp, a, sp), o)
```
and if you just want to make the code in a particular solver really readable, you can easily define O and T in that solver's codebase.

> There might be computational benefits too.

In the particle filter case, there is obviously a potential computational benefit because we are iterating through states and getting the weight for only a single observation for each state (this was the reason for `ParticleFilters.obs_weight`). But in all the other cases I can think of, it is more efficient to create the distribution and iterate over it. Are there cases besides particle filtering where there is a computational advantage i.e. if there is a line in FIB, can you link to it?

### Questions that would need to be settled before putting this in
1. Would this be part of the core POMDPs.jl interface, or could we just put it in POMDPToolbox (n.b. I am very happy we decided to put `weighted_iterator` in POMDPToolbox (see #163)), and, if it goes in POMDPs, how would we present it? Is it "part of the explicit interface"? or is it just something periferal?
3. Having functions that start with capital letters goes against typical Julia style. Is this violation of that norm justified?

I guess my initial feeling is that **adding this is not worth the hassle of adding additional things to explain**, but I am not set in this. @rejuvyesh , @MaximeBouton any thoughts? @mykelk I feel like you value code readability and have wisdom about it. What do you think?

**Comment by mykelk** [comment]
I like readable, simple code. Can this be done as part of a separate package that sits on top of POMDPs.jl? We want to make it easy for problem writers. Making it easy for solution writers is important, but of a lesser priority since there are fewer solver writers.

**Comment by zsunberg** [comment]
I think the only way this might make things easier *for problem writers* is if they could implement `O` and `T` *in lieu of* `observation` and `transition`, but that seems technically complicated.

**Comment by mykelk** [comment]
Actually, I think we can do it. Let's discuss next week if you're around.

**Comment by zsunberg** [comment]
Yeah, of course we *can* do it. The question is whether the extra complexity/explaining/confusion would be worth it. I'll be leaving on the 20th - I think we decided that we won't overlap.

If we really want to make it easier to express problems, I think we should work on something like this: https://github.com/JuliaPOMDP/QuickPOMDPs.jl

**Comment by dressel** [comment]
You would see computational benefits any time you only need to call a single observation (as opposed to iterating over them). The most obvious example is the belief update for a belief over a discrete state space. You don't need a distribution over observations; you need the probability of the observation received. If you return a distribution, which likely contains vectors, that's going to be way inefficient. Belief updating is a crucial inner loop; there are other examples (FIB, like you mention), but this one is critical.

It is more stuff to explain but it is something extra---by default it would be implemented as a wrapper to the already defined `transition` and `observation` functions.

I think allowing people to define O and T instead of observation and transition functions would be fantastic, but possibly complicated. It is always sad seeing the life seep from AA228 students when you tell them that the O and T functions they are used to are not used in POMDPs.jl

**Comment by mykelk** [comment]
I think I'll be around briefly on the 18th, say 2pm?

Also, is something like [PLite.jl](https://github.com/sisl/PLite.jl/tree/master/docs) what you had in mind? @haoyio made it a couple years ago.

**Comment by zsunberg** [comment]
> The most obvious example is the belief update for a belief over a discrete state space. You don't need a distribution over observations; you need the probability of the observation received.

I see - didn't remember that this is the case with any belief update. It is the same case as with particle filters. Perhaps `ParticleFilters.obs_weight` should be moved to POMDPs or POMDPToolbox and/or renamed so that it can be used in other packages. Are there any cases where there is a performance benefit with `T`? (A minor note is that these performance slowdowns can be avoided with clever distributions (i.e. lazy evaluation), but we probably don't want to make people do that)

>  It is always sad seeing the life seep from AA228 students when you tell them that the O and T functions they are used to are not used in POMDPs.jl

Yes, with the current interface, there is way too much life seepage. The question is should we reduce this by adding to the core interface or by building simpler, more limited interfaces on top of it that compile down to POMDPs.jl models?

How easy is it actually to define things in terms of `O` and `T`? Can we write out some simple problems? Tiger, Baby, Gridworld?

**Comment by zsunberg** [comment]
@mykelk yes, like PLite. I can meet on the 18th at 2. @dressel will you be there?

**Comment by dressel** [comment]
Sure

**Comment by zsunberg** [comment]
Talked with @mykelk . We think the best thing to do is move `ParticleFilters.obs_weight` to POMDPToolbox. `O` and `T` will not be provided by POMDPs or POMDPToolbox for us in solvers or updaters. If you, @dressel, (or someone else) want to add an interface *for problem writers* that allows problem definitions in terms of `O` and `T` in [QuickPOMDPs.jl](https://github.com/JuliaPOMDP/QuickPOMDPs.jl) or another package, that would be really awesome!

**Comment by zsunberg** [comment]
An interface that allows problem specification with O and T has been implemented in JuliaPOMDP/QuickPOMDPs.jl#1
