### ISSUE TITLE
Utility TerminalState type

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#197]
Note: this would not change the POMDPs.jl interface, and would only go in a toolbox package.

I think we should provide a `TerminalState` type and an instance of this type
```julia
struct TerminalState end
terminalstate = TerminalState()
POMDPs.isterminal(::Union{MDP,POMDP}, ::TerminalState) = true
```
for people to use in the common case that they have some simple representation for normal states (e.g. `SVector{2, Int}` for grid world), but also have a terminal state.

That way they can make their problems subtypes of e.g. `MDP{Union{MyState, TerminalState}, MyAct}` instead of creating custom state types.

This issue is just a stub; will add more description when I get the chance.

**Comment by johannes-fischer** [comment]
I have just started using JuliaPOMDPs recently, and came across a similar problem: I needed terminal actions. One obvious way to solve this is using a terminal state, as you propose. For me that didn't work because I am working with information measures like entropy. That requires that the states still represent the posterior belief, even after a terminal action was chosen. If all posterior states are the terminal state then the entropy will be zero and hence meaningless.
What I found in pomdp.jl was
`isterminal_obs(problem::POMDP, observation) = false`, however I haven't found it being used anywhere in the framework. I extended the idea and added 
```
isterminal_act(problem::Union{POMDP,MDP}, action) = false
isterminal(problem::POMDP, state, action, observation) = isterminal(problem, state, action) || isterminal_obs(problem, observation)
isterminal(problem::Union{POMDP,MDP}, state, action) = isterminal(problem, state) || isterminal_act(problem, action)
```
to accomodate terminal actions as well. To make this work, I had to change the previous
`isterminal(problem, state)` to `isterminal(problem, state, action, observation)` whereever it occurs. Most important in POMDPToolbox in the various simulators: rollout.jl, history_recorder.jl, stepthrough.jl
And it would have to be changed in all MCTS-based solvers.

**Comment by zsunberg** [comment]
Hi @johannes-fischer,

Thanks for chiming in! That is indeed an interesting case. You are right that `isterminal_obs` has been neglected, in fact I think we should remove it (#48).

If your reward is based on the entropy, then the problem is not strictly a POMDP - do you know if it is part of another class such as rho-POMDPs? It may be better in the POMDPs framework to represent it as an `MDP` on the belief space in this case.

Perhaps there is also an opportunity for us to create an interface extension to support a larger class of problems, such as rho-POMDPs.

In any case, I hope it has not been too hard for you to adapt the solvers to your needs!

**Comment by johannes-fischer** [comment]
Hi,

Thanks for your reply! At the moment I am looking at variants of the LightDark problem with the usual reward function. The entropy is just considered in the belief nodes of the solver rather than in the POMDP reward formulation. But that could surely be reformulated as a rho-POMDP.

Initially I used the SimpleLightDark problem from your ContinuousPOMDPTreeSearchExperiments repo. There the terminal action results in transitioning to an integer outside of the actual (bounded) state space, thereby identifying it as a "terminal state". In this setting, solvers trying to minimize entropy immediately chose the terminal action as the first action, because that concentrated the belief in this terminal state, which means minimal entropy. So I am not sure if the desired behaviour can be achieved using a terminal state instead of a terminal action. The terminal action on the other side leaves the belief unchanged and hence allows for calculation of the posterior entropy.

> In any case, I hope it has not been too hard for you to adapt the solvers to your needs!

The more I understand how the framwork works, the more I like it, thanks for the great work!

**Comment by zsunberg** [comment]
Thanks - that is really encouraging! :)

Yes, I see how taking an action that transitions to the terminal state makes the posterior entropy zero. If the solver only seeks to reduce entropy, then indeed, the best action to take in SimpleLightDark is always `0`, even if there is huge cost. As you have realized, a pure entropy-based solver is thus ill-suited to solve the SimpleLightDark problem as it is coded now.

The goal of a POMDP is, by definition, to maximize the expected future reward regardless of the entropy, so I think this example by itself is not enough reason to add support for terminal actions to all the solvers.

It would definitely be reasonable to have an extension to the interface that deals with entropy and might have terminal actions, and a particular solver might be designed to consider terminal actions, but it would take some thought about what the definition of a terminal action is. Does it need to always cause a transition to a terminal state? Does the simulation end right there and not transition into any state? Does the state remain unchanged?

I hope that makes sense! If you want to keep discussing, can you describe the "desired behavior" you were looking for?
