### ISSUE TITLE
horizon not a function for POMDPs

### ISSUE THREAD

**Issue by tawheeler** [JuliaPOMDP/POMDPs.jl#227]
I see that `discount` is an optional function for POMDPs, as it should be.
Is there a reason why `horizon` is not? Is that always a property of the solver?

**Comment by zsunberg** [comment]
Right now, we assume that all problems are infinite-horizon discounted problems with a discount factor (that may be 1). We deemed this the most general formulation because finite horizon problems can be represented by augmenting the state to include time and making states at the horizon terminal.

If we want to provide an interface for solvers to take advantage of the time structure in a finite horizon problem, I think the best way is to make a package called FiniteHorizonPOMDPs with, e.g.
```julia
abstract type FiniteHorizonPOMDP{S,A,O} <: POMDP{Tuple{S,Int}, A, O} end
```

**Comment by zsunberg** [comment]
That way all current solvers will be able to handle finite horizon problems out of the box (inefficiently, of course), but some can also take advantage of the finiteness if they choose to.

**Comment by tawheeler** [comment]
Thanks. I like how finite horizon POMDPs can be reduced to infinite horizon POMDPs.
