### ISSUE TITLE
Use :s′ instead of :sp for DDN Node names?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#278]
There is a unicode "prime" symbol (latex: `\prime`), so we could make the next state node `:s′` instead of `:sp`. The downsides of this are that people can't type it on their keyboards directly and it looks almost like the single quote, `'` (or maybe exactly like it?). Is this better or worse for the world?

**Comment by MaximeBouton** [comment]
I am not in favor of this: 
- as you said, it is easy to confuse with `'` 
- I found maintaining code with unicode symbols a bit tedious in the past, if you don't have the right extension on the editor. In that case, I don't think `:s′` is significantly more readable than `:sp` such that it is worth it.

**Comment by lassepe** [comment]
I agree with @MaximeBouton. In addition to what has been mentioned:
1. it requires more typing (also, because auto completion in many settings only start completing after the second character has been entered)
2. even worse than confusion with `s'` is the fact that people may oversee the "\`" completely and confuse it with plain `s`.
