### ISSUE TITLE
Getting LoadError when using POMDPSolve for the Tiger Problem

### ISSUE THREAD

**Issue by enter802** [JuliaPOMDP/POMDPs.jl#296]
I am getting "LoadError" (see screenshot) when I try to run the following code:

````
using POMDPSolve
using POMDPs
using POMDPModels
using POMDPFiles
using POMDPTesting
using POMDPPolicies
using Test

m = TigerPOMDP()
solver = POMDPSolveSolver()
policy = solve(solver, m)
````

Not sure why though.  The example under [quickstart](https://github.com/JuliaPOMDP/POMDPs.jl) runs pretty smoothly though. Am I missing something here?

![Capture](https://user-images.githubusercontent.com/9440833/79030425-e067c880-7b66-11ea-91ce-3a501511a7c2.PNG)

**Comment by zsunberg** [comment]
Thanks for reporting the error. The quickstart example on the POMDPs.jl readme uses QMDP which is written natively in julia.

POMDPSolve.jl, on the other hand, translates the pomdp to a file and then uses a binary executable (`<path to POMDPSolve package>\deps\pomdp-solve-master\src\pomdp-solve`). This executable should be automatically installed when you install POMDPSolve.jl, however there was apparently an error because windows cannot find the executable.

We have not supported POMDPSolve very thoroughly because it is a bit old. I would recommend switching to IncrementalPruning.jl, which is written in pure julia, or SARSOP.jl, which uses a binary executable, but we recently did a lot of work making the installation more robust on all platforms, so it should work well on windows. SARSOP is also a much more modern and capable algorithm than the ones in pomdp-solve.

**Comment by zsunberg** [comment]
To fix this error we should eventually make a POMDPsolve_jll.jl package like we did with SARSOP, but I don't know if anyone has the time to do it atm

**Comment by enter802** [comment]
Thank you for your prompt response. But unfortunately, despite POMDPSolve being old, I really need to use it since my course-defined-project requires me to use the algorithms listed under that (witness algorithm, linear support, etc.). So I was really hoping it would work out. I would really appreciate if someone could resolve the issue!

**Comment by mykelk** [comment]
I just pushed https://github.com/JuliaPOMDP/POMDPSolve.jl/commit/b9d26bb7ccb73e2ee5afc4d4ff865b5ca418c80e to fix an issue that can arise when working with directories on Windows. Grab that version off of master and then be sure to run `] build POMDPSolve`.

**Comment by mykelk** [comment]
@zsunberg Do you want to tag a version for that?

**Comment by enter802** [comment]
> I just pushed [JuliaPOMDP/POMDPSolve.jl@b9d26bb](https://github.com/JuliaPOMDP/POMDPSolve.jl/commit/b9d26bb7ccb73e2ee5afc4d4ff865b5ca418c80e) to fix an issue that can arise when working with directories on Windows. Grab that version off of master and then be sure to run `] build POMDPSolve`.

This is the error I get when I tried that.

![Capture](https://user-images.githubusercontent.com/9440833/79035598-297f4300-7b8e-11ea-89c3-20796eff7ea0.PNG)

**Comment by mykelk** [comment]
We haven't tagged a release yet, so you'll need to do `] add POMDPSolve#master`.

**Comment by enter802** [comment]
> We haven't tagged a release yet, so you'll need to do `] add POMDPSolve#master`.

Now a slightly different error:
![Capture](https://user-images.githubusercontent.com/9440833/79037070-12dfe880-7b9c-11ea-9c92-250a133f2a94.PNG)

**Comment by mykelk** [comment]
It looks like unzip isn't on your path. I just pushed a change so that it uses the 7z that comes with Julia.

**Comment by zsunberg** [comment]
Ah shoot I just tried to make a similar change but you were faster @mykelk haha

**Comment by mykelk** [comment]
@zsunberg Maybe your fix is better?

**Comment by enter802** [comment]
> It looks like unzip isn't on your path. I just pushed a change so that it uses the 7z that comes with Julia.

It is working now! Thanks a lot for your hard work. I really appreciate your input to the community.

**Comment by enter802** [comment]
> Ah shoot I just tried to make a similar change but you were faster @mykelk haha

Thank you for trying!

**Comment by MaximeBouton** [comment]
Maybe I can start looking at the jll package. There is no github repo for the source code right? 

Also, does anyone know how the windows binaries were compiled: https://github.com/JuliaPOMDP/POMDPSolve.jl/blob/master/deps/build.jl#L47

**Comment by mykelk** [comment]
@MaximeBouton that would be awesome! You can download the source here:
https://www.pomdp.org/code/
I found this patched one on github, but it is for an older version (5.1 instead of 5.4):
https://github.com/cmansley/pomdp-solve/commit/09b3fcf29e56dde10eb5c57989ef3fd472207d2b
So, I would recommend getting it from Tony Canssandra's webpage (ond pomdp.org) since he wrote it.

I compiled the binaries that you are referring to. A jll package is definitely the way to go!

**Comment by MaximeBouton** [comment]
ok it turns out being a bit more involved than I thought, I am getting different errors on MacOS and windows when cross compiling. I am working with the pomdp.org source.
I will try to debug it but it might take some time. 

For the windows build, did you have to do anything special for it to compile?

**Comment by mykelk** [comment]
We should probably start a thread over on POMDPSolve.jl. For Windows, I sent an email to you with the directory I used for the successful build. I did that build in 2016. I don't recall whether I had to do anything special. I'm happy to take a look at any error messages you get.
