### ISSUE TITLE
CI badges look scary

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPs.jl#478]
Entering the README with the CI badges below is pretty scary. Users may conclude that the package is broken/unmaintained. The breakage is not in the actual tests but in the documentation.

![image](https://user-images.githubusercontent.com/10076790/233997425-b58f3bda-9b22-4958-bf2a-04958d514a79.png)

**Comment by mykelk** [comment]
So very true.

**Comment by WhiffleFish** [comment]
I believe it's because the docs depend on master for POMDPs but the latest registered version for POMDPTools. The docs then fail to build because only the master version of POMDPTools is compatible with the master version of POMDPs.

This could possibly be fixed by also pushing POMDPTools src to the load path in `docs/make.jl`. However this would likely still break because other dependencies (POMDPModels and QuickPOMDPs) are not tested against master POMDPs.jl.

**Comment by zsunberg** [comment]
Hmmm... now the tests aren't even passing due to some things that look outdated. in POMDPTools test_belief.jl . @WhiffleFish can we talk about this tomorrow?

**Comment by zsunberg** [comment]
The broken tests are from a (correct) change I made to POMDPModels. A few tests in POMDPTools were incorrect, but also happened to work with the old version of POMDPModels

**Comment by zsunberg** [comment]
Ok, should be fixed now docs build with both POMDPs and POMDPTools masters

**Comment by zsunberg** [comment]
Fixed with #479
