### ISSUE TITLE
isterminal() for observations?

### ISSUE THREAD

**Issue by ebalaban** [JuliaPOMDP/POMDPs.jl#48]
Since we give "special" status to terminal states, should we also be able to distinguish terminal observations? I used to have a sanity check in DESPOT where I verified whether a terminal observation was generated upon transition to a terminal state. It's not critical though. Does anyone else see any need for such a function?

**Comment by mykelk** [comment]
I'm okay with it.

**Comment by ebalaban** [comment]
Any objections to this? If not, I'll go ahead and put it in tomorrow late afternoon/evening.

**Comment by etotheipluspi** [comment]
Just to clarify, a terminal observation has a one-to-one mapping between itself and a terminal state, correct? I think we would have to make this clear, because this could lead to confusion in some cases. For example, if we take the grid world MDP and turn into a POMDP by adding noise to the position of the agent, in some cases the agent may receive a terminal state observation when its not in a terminal state. Recall that the positive reward states in grid world are terminal. In this case, would it make sense to have a terminal observation?

I see the need for something like a terminal observation, but I just want to make sure it's role and how it should be implemented are clear.

**Comment by mykelk** [comment]
I think the only sensible way to do this is to assume that you get a terminal observation if and only if you are in a terminal state.

**Comment by ebalaban** [comment]
I agree with @mykelk.

**Comment by etotheipluspi** [comment]
Sounds good, I'm for it.

**Comment by ebalaban** [comment]
Great, thanks! Implemented with 6e3fd7e.

**Comment by zsunberg** [comment]
I think we should consider removing `isterminal_obs`. As noted by @johannes-fischer in #197, it is rarely (never?) used in any solvers or simulators. I can't think of a case where `isterminal` called on the state is insufficient, and if `isterminal_obs` actually conforms to the definition we established above

> you get a terminal observation if and only if you are in a terminal state

it requires problem writers to be consistent, and it is hard to communicate this assumption to all parties. Does anyone object to removing this?

**Comment by ebalaban** [comment]
I suppose I can live without `isterminal_obs`. A related question still arises though: should we handle terminal beliefs in some unified manner or is it every solver on its own, as long as `isterminal` for states is provided?
