### ISSUE TITLE
Not actually testing on MacOS/Windows

### ISSUE THREAD

**Issue by WhiffleFish** [JuliaPOMDP/POMDPs.jl#481]
All CI badges point to the same link.

We're only actually testing on `ubuntu-latest` as made evident in `CI.yml`.

**Comment by zsunberg** [comment]
My bad

![image](https://user-images.githubusercontent.com/4240491/235006753-24eb6a38-6488-433b-81e0-1512f95ca1c4.png)

**Comment by zsunberg** [comment]
We should definitely not *lie* on the README, but there are two solutions:
1) actually test on all OSs
2) just have one badge

I don't think there is any OS-specific code, so maybe we would be better citizens with solution (2) not taking up the resources. Also, at least in the olden days, testing on Windows and Mac was super annoying because it would take a long time for a machine to become available. On the other hand, people might be more confident in using it if they see that their OS has a green box next to it (though if they know what the green box means, they probably realize that it doesn't matter).

**Comment by rejuvyesh** [comment]
I think it's easy enough to test on multiple os with: `runs-on: ${{ matrix.os }}` and setting up the `matrix.os` appropriately. IMO we _should_ test on the major 3 OS.

**Comment by zsunberg** [comment]
This was fixed with #486
