### ISSUE TITLE
Value bounds

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#54]
The MCVI solver requires a function that estimates an upper bound on the value of a state. The tighter the bound the better the performance. Is anyone opposed to adding a function of the form
```julia
upperbound(pomdp::POMDP, s::State)
```
I'm wondering if this function would be useful in other solvers as well. SARSOP uses these types of bounds, but something like value iteration can be used to estimate these since the problem is discrete. In MCVI, the problem is continuous, so a user implementation is needed. We can also add a ```lowerbound``` function if it makes sense.

What does everyone think?

**Comment by ebalaban** [comment]
I needed this for DESPOT as well, so I just ended up implementing upper and lower bound estimators as optional parameters for the solver. If the user does not supply their favorite estimators, the default ones are used. In a lot of cases these estimators will be problem-specific, so I guess it would be good to try to come up with a common interface so that they can be reused. Mine take in beliefs, but it may be possible to implement them efficiently with individual states also. If we do add this to the interface, we should define UpperBound and LowerBound types, so that different estimators can be defined and some precomputed information can be stored between calls.

**Comment by zsunberg** [comment]
Yeah, It seems like there could be multiple ways estimate the bounds for
the same problem, so there should be more arguments than just the pomdp and
the state. As @ebalaban did, I think we'll need to make some bound
estimator types.

In order to keep the interface less cluttered, should we think about
putting this in another package, POMDPBounds.jl, or would that be too small
of a package?

**Comment by zsunberg** [comment]
Or perhaps we should make a package called POMDPValues.jl or something and include both bounds and unbiased estimates like rollouts and the value function in #52 . I think both of these things could be separated from the core interface.

**Comment by etotheipluspi** [comment]
I would prefer to not add additional types (but open to changing my stance). Any pre-computed values can be stored in the pomdp without being too messy:

```julia
type LowerBounds
    state_bounds::Array{Float64}
end

type UpperBounds
    state_bounds::Array{Float64}
end

type MyPOMDP 
    upperbounds::UpperBounds
    lowerbounds::LowerBounds
end
```

**Comment by ebalaban** [comment]
Well, if we do that, we'd be mixing problem definition and problem solution. Some solvers don't estimate upper and lower bounds. Do we want to require problem writers to include data storage for our bound estimators in their POMDP types?

**Comment by zsunberg** [comment]
Yeah, I agree with @ebalaban . I think that while upper and lower bounds are sometimes fundamental properties of the problem, they are often estimated by something like QMDP or by running a suboptimal policy. Hence they are not fundamentally a part of the problem, so they shouldn't be in the pomdp object.

**Comment by mykelk** [comment]
Yeah, what Zach and Edward said.

**Comment by etotheipluspi** [comment]
But we are asking the users to define the bounds when they implement their problem, so they are a part of the problem definition. The way I see it, the more types/functions/modules we add to the framework the more intimidating the package is for new users. Of course I could be wrong about this, but I would like to keep the interface minimalist. I would also be ok with the bounds functions being optional, solver specific arguments which is what @ebalaban did for DESPOT.

**Comment by zsunberg** [comment]
I agree that the interface is getting kind of intimidating. That's why I
think we may want to start breaking things out into additional interface
packages. Then POMDPs.jl can focus just on the core concepts, and we can
add one line to the documentation:

If you are using or implementing a solver that can benefit from value
bounds information, see POMDPValues.jl.

Then if problem writers or solver writers want to deal with bounds or
value(), they can look at the extensive documentation/fully featured
interface available in POMDPValues.jl. And if they don't care about bounds,
they will never have to see it again.

**Comment by etotheipluspi** [comment]
Alright, I like that idea. Would POMDPValues.jl just define the bound types and the corresponding methods, or would it also have some default implementation for computing bounds?

**Comment by ebalaban** [comment]
I think putting this into a separate package is a good idea. The package would also be the place for generic implementations of bound estimators and perhaps value estimators as well, as @zsunberg suggested. POMDPValues.jl sounds a bit ambiguous though, maybe POMDPValueEstimation.jl?

**Comment by etotheipluspi** [comment]
We should get this issue wrapped up before the paper is sent out. 

I think there are two main issues to resolve here:
1. What do we call the additional interface module: POMDPValues, POMDPValueEstimation, POMDPBounds or something else?
2. What should go in the interface? Some candidates:
```julia
abstract Bound

function upper_bound{B}(b::Bound, pomdp::POMDP, b::B) # what should the third argument be?
function lower{B}(b::Bound, pomdp::POMDP, b::B) 

function init_upper_bound(b::Bound, pomdp::POMDP)
function init_lower_bound(b::Bound, pomdp::POMPD)
```
@ebalaban @rejuvyesh you guys probably have the most insight into this.

**Comment by etotheipluspi** [comment]
I just talked to @mykelk , and he prefers POMDPBounds, so I created a new repo under JuliaPOMDP that includes the type and functions outlined above. 

Let's still iron out the details of this. We can always change the names as we see fit.

**Comment by rejuvyesh** [comment]
I think this formulation is flexible enough for all cases. We can create a `Bound` object to contain whatever is necessary for the particular solver/problem. Third argument would be belief/state as required.

**Comment by ebalaban** [comment]
I am fine with POMDPBounds for now. The initial interface looks reasonable as well. Thanks, @etotheipluspi, for setting this up.

**Comment by etotheipluspi** [comment]
Closing this, please leave and issues in [POMDPBounds](https://github.com/JuliaPOMDP/POMDPBounds.jl)
