### ISSUE TITLE
MDPs with parametric types

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#60]
What is the best way to treat MDPs with the parametric template:
```julia
abstract POMDP{S,A,O}
```

@zsunberg proposed to do this:
```julia
typealias MDP{S,A} POMDP{S,A,S}
```
which I think is pretty clever. 

The other option is to have a default Nullable type for observations that can be overwritten when the user has a POMDP. Thoughts?

**Comment by mykelk** [comment]
I like the method of @zsunberg by far the best.

**Comment by zsunberg** [comment]
I'm starting to think that we would be better off having `MDP` and `POMDP` as separate abstract types.

The following example illustrates the problem with the approach above. In [GenerativeModels.jl](https://groups.google.com/forum/#!topic/pomdps-users/wpvKUNqTwo0), I would like to have two `generate()` functions - one for POMDPs and one for MDPs:
```julia
(s', o, r) = generate{S,A,O}(p::POMDP{S,A,O}, s::S, a::A, rng::AbstractRNG)
```
and
```julia
(s', r) = generate{S,A}(p::MDP{S,A}, s::S, a::A, rng::AbstractRNG)
```
The problem is, if we use `typealias MDP{S,A} POMDP{S,A,S}` and I define a POMDP with the same state and observation types (this is common, as the observation is often just a state with noise added), then the MDP `generate` method will erroneously be called. I think this problem will show up in other places as well.

The main side effect of using separate types is that we would have to have two versions of many interface functions (or we could make both subtypes of `AbstractMDP` and declare the methods with `AbstractMDP` arguments). This doesn't seem that bad to me.

What do ya'll think? Are there any other side effects that I am missing?

**Comment by mykelk** [comment]
Why not just use the top function? You'd just return (s', s', r). Right?

**Comment by zsunberg** [comment]
Yeah, that could be done, though I don't think it would be that elegant -
for a default implementation, there would have to be an implementation of
`observation()` for first argument `::POMDP{S,AS}` that just returns the
true state... this could get confusing if that is floating around in the
POMDPs namespace whenever GenerativeModels` is imported.

What about `abstract MDP{S,A} <: POMDP{S,A,S}`. Then the set of MDPs is a
special subset of the set of POMDPs that use the same type for states and
observations. That would make me happy.

Is "All POMDP solvers should be able to solve an `MDP`" a goal of this
project? My initial thought is 'no'.

**Comment by mykelk** [comment]
I vote for making you happy.

**Comment by zsunberg** [comment]
Ok, I'll go forward with `abstract MDP{S,A} <: POMDP{S,A,S}` for now

**Comment by etotheipluspi** [comment]
I'm also happy with @zsunberg's proposal. I also agree that all POMDP solvers should solve and MDP is not something we should be going for. However, all MDP solvers should be able to solve a POMDP (for bounds), and this should be doable with @zsunberg type proposal.

**Comment by zsunberg** [comment]
Hmm... @etotheipluspi , when you say "all MDP solvers should be able to solve a POMDP", this might get a little complicated. If we go with `abstract MDP{S,A} <: POMDP{S,A,S}` and write solvers that solve an MDP, they won't be able to solve a POMDP{S,A,O} where S is not the same as O out of the box. Maybe we need a function that creates a fully observable version, i.e.
```julia
fully_observable{S,A,O}(::POMDP{S,A,O}) -> MDP{S,A}
```
We could have a default implementation of this that returns a wrapper like this:
```julia
type FullyObservable{S,A,O} <: MDP{S,A}
    original::POMDP{S,A,O}
end
or the problem writer could implement their own version if they want something more efficient.

Of course, alternatively, we could just say that MDP solvers should be written for any `POMDP{S,A,O}`, and it is assumed that the solver solves the fully observable version of the problem, but I really don't like this because it is not explicit. (I was personally envisioning that if people wanted to solve a fully observable version of their problem, they would just write their own MDP type)

I think if we want to, we can kick this down the road and figure out the details later.

**Comment by zsunberg** [comment]
I have run into a potential workflow awkwardness if we keep 

```julia
abstract MDP{S,A} <: POMDP{S,A,S}
```

Often researchers will start out with an MDP and solve that first, and then later add partial observability. So, when they create the MDP, they'll write some code like this (`MyS`, `MyA`, and `MyO` are custom state, action, and observation types):

```julia
type MyMDP <: MDP{MyS, MyA}
    ...
end

function transition(::MyMDP, ::MyS, ::MyA, ...)
    ...
end

...
```

If they want to reuse their MDP code in their POMDP, they will probably have to resort to some sort of composition scheme like this:

```julia
type MyPOMDP <: POMDP{MyS, MyA, MyO}
    mdp::MyMDP
    ...
end

transition(p::MyPOMDP, ::MyS, ::MyA, ...) = transition(p.mdp, ...)

...

```

Are we OK with this happening? In one sense, it is reasonable because every POMDP has an underlying MDP (Defined by (S,A,T,R) in the (S,A,T,R,O,Z) definition).

If we don't like this, other options include:
1. Getting rid of the `MDP` type altogether
2. Stipulating that MDP solvers should be able to handle any `POMDP{S,A,O}` and the solver is expected to solve the fully observable version

Do we need to make a change, or are we OK with people often using the composition approach above?

**Comment by mykelk** [comment]
I have no strong opinions here.

**Comment by ebalaban** [comment]
Hm... I think it might be cleaner to just have separate abstract MDP and POMDP types. I don't think we should set compatibility expectations for either POMDP or MDP solvers. The overhead of creating two versions of functions like `generate` might be worth it, especially if the core portion of the code can be put in a common function.

**Comment by zsunberg** [comment]
I would be OK with having two separate types. It is easy enough to write functions like `f{S,A}(::Union{MDP{S,A}, POMDP{S,A}})`. I maybe very slightly prefer `MDP{S,A} <: POMDP{S,A,S}` but I can't think of any really strong arguments either way.

**Comment by mykelk** [comment]
I'd like to avoid Union to types.

**Comment by ebalaban** [comment]
I don't like creating unions of types either, but if some messiness is unavoidable, I'd rather have it on the methods level rather than on the data types level. My guess is that most of the time MDP and POMDP methods will be naturally separated. For the remaining cases (e.g. generate()), the users could decide for themselves on how to handle them. They can write two independent functions, they can create two interface functions calling some common code, or (if that's their style) they can create a function with a type union as an argument.

**Comment by zsunberg** [comment]
@mykelk and/or @ebalaban , can you comment on why you would like to avoid unions? I am currently leaning towards making MDP and POMDP separate types, and I think declaring things like this
```julia
"""
    transition{S,A,O}(pomdp::POMDP{S,A,O}, state::S, action::A, distribution::AbstractDistribution{S}=create_transition_distribution(pomdp))
    transition{S,A}(mdp::MDP{S,A, state::S, action::A, distribution::AbstractDistribution{S}=create_transition_distribution(mdp))

Return the transition distribution from the current state-action pair
"""
@pomdp_func transition{S,A}(problem::Union{MDP{S,A},POMDP{S,A}}, state::S, action::A, distribution::AbstractDistribution{S}=create_transition_distribution(problem))
```
will make documentation easier to maintain, and, more importantly, *easier to read* compared to having two separate functions in the docs. Using unions as function argument types seems pretty benign to me.

Also, I want to know why you dislike them so that I can better advise people when they as about doing this in their projects :)

**Comment by etotheipluspi** [comment]
I agree with @zsunberg on the union approach. We are not enforcing users to create union types, so there is no added complexity for problem writers. Unions in the POMDPs.jl source make it cleaner. 

Unless there is a large computational overhead on using union, I think we should do it

**Comment by mykelk** [comment]
I'm fine with it.

**Comment by tawheeler** [comment]
From [Steven Johnson](https://groups.google.com/forum/#!topic/julia-users/hG_nXh5eRD0): 

"In a function argument, type declarations have zero effect on performance.  It doesn't matter to the compiler whether you declare a function as `f(a)`, `f(a::Any)`, `f(a::Vector{Float64})`, or `f{T}(a::Union{Associative{Int,T}, AbstractVector{T}})`."
"The key thing to remember about Julia is that, each time you call a function `f(a)` with a different type of argument, Julia recompiles a new version of `f` specialized for that argument type, which is used for all subsequent calls for the same argument types.  This specialized version is just as fast as if you had explicitly typed `f(a::SomeType)` in the first place."
"Argument-type declarations are not for performance in Julia, they are a filter: they say "use this method for these types".  This is useful for multiple dispatch (if you have different methods depending on the argument types), for correctness (if your function will give unexpected/incorrect results for some types), and for clarity (to indicate clearly to the user what is expected to be passed to a function)."

"When you define a data structure, any abstract type for a field (whether it is a Union type or another abstract type like Associative) will be significantly slower than a concrete type."

Takeaway:
- the union would just be there for clarity and would not affect performance

**Comment by zsunberg** [comment]
Decided in the meeting today to have completely separate POMDP and MDP types.
